---
- hosts: consul_instances
  become: yes

  roles:
    - {role: brianshumate.consul, tags: ['consul', 'hashicorp']}

  vars:
    consul_datacenter: "homeserver"
    consul_acl_datacenter: "homeserver"
    consul_domain: "consul"
    consul_recursors: "{{ dns_nameservers }}"
    consul_syslog_enable: yes
    # Think carefully before modifying the following variables
    consul_iface: eth0 # TODO: This actually isn't being used anywhere in the upstream consul role, might be a bug
    consul_client_address: "0.0.0.0"
    consul_dnsmasq_enable: yes
    consul_acl_master_token_display: yes
    # Telemetry
    consul_config_custom:
      telemetry:
        disable_hostname: true
        prometheus_retention_time: "30s"
        statsd_address: "localhost:8125"

- hosts: vault_instances
  become: yes

  roles:
    - {role: brianshumate.vault, tags: ['vault', 'hashicorp']}

  vars:
    vault_cluster_name: "dc1"
    vault_datacenter: "homeserver"
    vault_domain: "consul"
    vault_ui: yes
    vault_cluster_disable: yes
    # Think carefully before modifying the following variables
    vault_iface: eth0
    # Telemetry
    vault_telemetry_enabled: yes
    vault_telemetry_disable_hostname: yes
    vault_prometheus_retention_time: "30s"
    vault_statsd_address: "localhost:8125"

- hosts: nomad_instances
  become: true

  vars_files:
    - vaulted_vars/nomad_sensitive.yml

  pre_tasks:
    - {import_tasks: tasks/cgroup_features.yml, tags: ['docker']}

  roles:
    - {role: geerlingguy.docker_arm, tags: ['docker']}
    - {role: brianshumate.nomad, tags: ['docker', 'nomad', 'hashicorp']}

  vars:
    nomad_datacenter: "homeserver"
    nomad_domain: "consul"
    nomad_use_consul: yes
    nomad_vault_enabled: yes
    nomad_docker_enable: yes
    # Don't set the network speed
    nomad_network_speed: 0
    # Think carefully before modifying the following variables
    nomad_iface: eth0
    nomad_network_interface: eth0
    nomad_bootstrap_expect: 1
    nomad_consul_address: "http://127.0.0.1:8500"
    nomad_vault_address: "http://active.vault.service.homeserver.consul:8200"
    # Telemetry
    nomad_config_custom:
      telemetry:
        prometheus_metrics: true
        statsd_address: "localhost:8125"
        disable_hostname: true
