---
- src: jason_riddle.amazon_ssm_agent
- src: jason_riddle.wpa_supplicant
- src: geerlingguy.docker_arm
- src: brianshumate.consul
- src: brianshumate.vault
- name: brianshumate.nomad
  src: https://github.com/ansible-community/ansible-nomad
  version: origin/master
