---
- hosts: all
  become: yes

  tasks:
    - name: Set bramble_mac_address fact.
      set_fact:
        bramble_mac_address: "{{ hostvars[inventory_hostname].ansible_eth0.macaddress }}"

    - name: Set bramble_hostname and bramble_ip_address fact.
      set_fact:
        bramble_hostname: "{{ mac_address_mapping[bramble_mac_address].hostname }}"
        bramble_ip_address: "{{ mac_address_mapping[bramble_mac_address].ip }}"
