---
- name: Enable required cgroup features.
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory'
    state: present
  register: cgroup_features

- name: Reboot immediately if cgroup features changed and wait for host to be available.
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 3
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 10
    test_command: whoami
  when: cgroup_features is changed
